# 1. Data
## 1.1 Load Data

In [2]:
import pandas as pd

df = pd.read_csv('Concrete_Data_Yeh.csv')
df.head()

,cement,slag,flyash,water,superplasticizer,coarseaggregate,fineaggregate,age,csMPa
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

## 1.2 Summarize the Data

In [3]:
df

,cement,slag,flyash,water,superplasticizer,coarseaggregate,fineaggregate,age,csMPa
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90,47.03
6,380.0,95.0,0.0,228.0,0.0,932.0,594.0,365,43.70
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28,36.45
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28,39.29
10,198.6,132.4,0.0,192.0,0.0,978.4,825.5,90,38.07
11,198.6,132.4,0.0,192.0,0.0,978.4,825.5,28,28.02
12,427.5,47.5,0.0,228.0,0.0,932.0,594.0,270,43.01
13,190.0,190.0,0.0,228.0,0.0,932.0,670.0,90,42.33
14,304.0,76.0,0.0,228.0,0.0,932.0,670.0,28,47.81
15,380.0,0.0,0.0,228.0,0.0,932.0,670.0,90,52.91
16,139.6,209.4,0.0,192.0,0.0,1047.0,806.9,90,39.36
17,342.0,38.0,0.0,228.0,0.0,932.0,670.0,365,56.14
18,380.0,95.0,0.0,228.0,0.0,932.0,594.0,90,40.56
19,475.0,0.0,0.0,228.0,0.0,932.0,594.0,180,42.62
20,427.5,47.5,0.0,228.0,0.0,932.0,594.0,180,41.84
21,139.6,209.4,0.0,192.0,0.0,1047.0,806.9,28,28.24
22,139.6,209.4,0.0,192.0,0.0,1047.0,806.9,3,8.06
23,139.6,209.4,0.0,192.0,0.0,1047.0,806.9,180,44.21
24,380.0,0.0,0.0,228.0,0.0,932.0,670.0,365,52.52
25,380.0,0.0,0.0,228.0,0.0,932.0,670.0,270,53.30
26,380.0,95.0,0.0,228.0,0.0,932.0,594.0,270,41.15
27,342.0,38.0,0.0,228.0,0.0,932.0,670.0,180,52.12
28,427.5,47.5,0.0,228.0,0.0,932.0,594.0,28,37.43
29,475.0,0.0,0.0,228.0,0.0,932.0,594.0,7,38.60
...,...,...,...,...,...,...,...,...,...
1000,141.9,166.6,129.7,173.5,10.9,882.6,785.3,28,44.61
1001,297.8,137.2,106.9,201.3,6.0,878.4,655.3,28,53.52
1002,321.3,164.2,0.0,190.5,4.6,870.0,774.0,28,57.22
1003,366.0,187.0,0.0,191.3,6.6,824.3,756.9,28,65.91
1004,279.8,128.9,100.4,172.4,9.5,825.1,804.9,28,52.83
1005,252.1,97.1,75.6,193.8,8.3,835.5,821.4,28,33.40
1006,164.6,0.0,150.4,181.6,11.7,1023.3,728.9,28,18.03
1007,155.6,243.5,0.0,180.3,10.7,1022.0,697.7,28,37.36
1008,160.2,188.0,146.4,203.2,11.3,828.7,709.7,28,35.31
1009,298.1,0.0,107.0,186.4,6.1,879.0,815.2,28,42.64
1010,317.9,0.0,126.5,209.7,5.7,860.5,736.6,28,40.06
1011,287.3,120.5,93.9,187.6,9.2,904.4,695.9,28,43.80
1012,325.6,166.4,0.0,174.0,8.9,881.6,790.0,28,61.24
1013,355.9,0.0,141.6,193.3,11.0,801.4,778.4,28,40.87
1014,132.0,206.5,160.9,178.9,5.5,866.9,735.6,28,33.31
1015,322.5,148.6,0.0,185.8,8.5,951.0,709.5,28,52.43
1016,164.2,0.0,200.1,181.2,12.6,849.3,846.0,28,15.09
1017,313.8,0.0,112.6,169.9,10.1,925.3,782.9,28,38.46
1018,321.4,0.0,127.9,182.5,11.5,870.1,779.7,28,37.27
1019,139.7,163.9,127.7,236.7,5.8,868.6,655.6,28,35.23
1020,288.4,121.0,0.0,177.4,7.0,907.9,829.5,28,42.14
1021,298.2,0.0,107.0,209.7,11.1,879.6,744.2,28,31.88
1022,264.5,111.0,86.5,195.5,5.9,832.6,790.4,28,41.54
1023,159.8,250.0,0.0,168.4,12.2,1049.3,688.2,28,39.46
1024,166.0,259.7,0.0,183.2,12.7,858.8,826.8,28,37.92
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [4]:
df.describe()

,cement,slag,flyash,water,superplasticizer,coarseaggregate,fineaggregate,age,csMPa
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

##  Observations:
-  From the data set we can find that there are no missing values for each column
-When we am looking at the data we can figure out most  of the features are components of concrete mixture and how much quantities is used for each column and age  column is  there to define how much day the concrete has been kept to cure
- Concrete compressive strength is the target variable and highest strength it achieved was 82.6 MPa, Minimum value it achieved was 2.3 MPa  and also keeping an average strength of 35.8 MPa all along.

## 1.3  Checking the Datatype and Missing values

In [5]:
df.isnull().sum()

cement              0
slag                0
flyash              0
water               0
superplasticizer    0
coarseaggregate     0
fineaggregate       0
age                 0
csMPa               0
dtype: int64

- From the line of code we can understand that there are no missing or null values
- Most of the data type is Float and age is  integer

In [6]:
df.duplicated
df.duplicated().sum()

25

- From here we checked for the duplicate values and  found out there are 25 duplicate values in the data set

In [7]:
df = df.drop_duplicates()

In [8]:
df.duplicated().sum()

0

- We have dropped the duplicates adn fixed the data set now the duplicates are 0